---
name:   Mahs Jong                    # The application display name
short:  mahsjong                      # A shortened name for reference
appid:  games.cornell607.mahsjong     # Application identifier for Mac, iOS, Android

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)

orientation: landscape              # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h

modules:                            # Modules to use other than core, graphics
    - audio
    - scene2

# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                        # The target platforms to build for
    - android                   # Android Studio
    - apple                     # XCode (note macOS and iOS use one project)
    - windows                   # Windows Sisual Studio
    - cmake                     # This supports all Desktop platfor G8AB3BC G8AB3BCD
