# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/walkerstrauss/cs4152/mahsjong/build/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/walkerstrauss/cs4152/mahsjong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake /Users/walkerstrauss/cs4152/mahsjong/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"headers\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/walkerstrauss/cs4152/mahsjong/CMakeFiles /Users/walkerstrauss/cs4152/mahsjong//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/walkerstrauss/cs4152/mahsjong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mahsjong

# Build rule for target.
mahsjong: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mahsjong
.PHONY : mahsjong

# fast build rule for target.
mahsjong/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/build
.PHONY : mahsjong/fast

#=============================================================================
# Target rules for targets named cugl-core

# Build rule for target.
cugl-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cugl-core
.PHONY : cugl-core

# fast build rule for target.
cugl-core/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/CMakeFiles/cugl-core.dir/build.make cugl.dir/CMakeFiles/cugl-core.dir/build
.PHONY : cugl-core/fast

#=============================================================================
# Target rules for targets named cugl-graphics

# Build rule for target.
cugl-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cugl-graphics
.PHONY : cugl-graphics

# fast build rule for target.
cugl-graphics/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/CMakeFiles/cugl-graphics.dir/build.make cugl.dir/CMakeFiles/cugl-graphics.dir/build
.PHONY : cugl-graphics/fast

#=============================================================================
# Target rules for targets named cugl-audio

# Build rule for target.
cugl-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cugl-audio
.PHONY : cugl-audio

# fast build rule for target.
cugl-audio/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/CMakeFiles/cugl-audio.dir/build.make cugl.dir/CMakeFiles/cugl-audio.dir/build
.PHONY : cugl-audio/fast

#=============================================================================
# Target rules for targets named cugl-scene2

# Build rule for target.
cugl-scene2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cugl-scene2
.PHONY : cugl-scene2

# fast build rule for target.
cugl-scene2/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/CMakeFiles/cugl-scene2.dir/build.make cugl.dir/CMakeFiles/cugl-scene2.dir/build
.PHONY : cugl-scene2/fast

#=============================================================================
# Target rules for targets named cugl-netcode

# Build rule for target.
cugl-netcode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cugl-netcode
.PHONY : cugl-netcode

# fast build rule for target.
cugl-netcode/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/CMakeFiles/cugl-netcode.dir/build.make cugl.dir/CMakeFiles/cugl-netcode.dir/build
.PHONY : cugl-netcode/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/sdl_headers_copy.dir/build.make cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/SDL2main.dir/build.make cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/SDL2-static.dir/build.make cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/uninstall.dir/build.make cugl.dir/sdl2pckg.dir/sdl2/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named SDL2_image

# Build rule for target.
SDL2_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_image
.PHONY : SDL2_image

# fast build rule for target.
SDL2_image/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2image/CMakeFiles/SDL2_image.dir/build.make cugl.dir/sdl2pckg.dir/sdl2image/CMakeFiles/SDL2_image.dir/build
.PHONY : SDL2_image/fast

#=============================================================================
# Target rules for targets named SDL2_ttf

# Build rule for target.
SDL2_ttf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf
.PHONY : SDL2_ttf

# fast build rule for target.
SDL2_ttf/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2ttf/CMakeFiles/SDL2_ttf.dir/build.make cugl.dir/sdl2pckg.dir/sdl2ttf/CMakeFiles/SDL2_ttf.dir/build
.PHONY : SDL2_ttf/fast

#=============================================================================
# Target rules for targets named harfbuzz

# Build rule for target.
harfbuzz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harfbuzz
.PHONY : harfbuzz

# fast build rule for target.
harfbuzz/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2ttf/external/harfbuzz/CMakeFiles/harfbuzz.dir/build.make cugl.dir/sdl2pckg.dir/sdl2ttf/external/harfbuzz/CMakeFiles/harfbuzz.dir/build
.PHONY : harfbuzz/fast

#=============================================================================
# Target rules for targets named harfbuzz-subset

# Build rule for target.
harfbuzz-subset: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harfbuzz-subset
.PHONY : harfbuzz-subset

# fast build rule for target.
harfbuzz-subset/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2ttf/external/harfbuzz/CMakeFiles/harfbuzz-subset.dir/build.make cugl.dir/sdl2pckg.dir/sdl2ttf/external/harfbuzz/CMakeFiles/harfbuzz-subset.dir/build
.PHONY : harfbuzz-subset/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2ttf/external/freetype/CMakeFiles/freetype.dir/build.make cugl.dir/sdl2pckg.dir/sdl2ttf/external/freetype/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named SDL2_atk

# Build rule for target.
SDL2_atk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_atk
.PHONY : SDL2_atk

# fast build rule for target.
SDL2_atk/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/CMakeFiles/SDL2_atk.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/CMakeFiles/SDL2_atk.dir/build
.PHONY : SDL2_atk/fast

#=============================================================================
# Target rules for targets named ogg

# Build rule for target.
ogg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ogg
.PHONY : ogg

# fast build rule for target.
ogg/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/ogg/CMakeFiles/ogg.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/ogg/CMakeFiles/ogg.dir/build
.PHONY : ogg/fast

#=============================================================================
# Target rules for targets named FLAC

# Build rule for target.
FLAC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FLAC
.PHONY : FLAC

# fast build rule for target.
FLAC/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/libFLAC/CMakeFiles/FLAC.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/libFLAC/CMakeFiles/FLAC.dir/build
.PHONY : FLAC/fast

#=============================================================================
# Target rules for targets named replaygain_analysis

# Build rule for target.
replaygain_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replaygain_analysis
.PHONY : replaygain_analysis

# fast build rule for target.
replaygain_analysis/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/replaygain_analysis/CMakeFiles/replaygain_analysis.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/replaygain_analysis/CMakeFiles/replaygain_analysis.dir/build
.PHONY : replaygain_analysis/fast

#=============================================================================
# Target rules for targets named replaygain_synthesis

# Build rule for target.
replaygain_synthesis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replaygain_synthesis
.PHONY : replaygain_synthesis

# fast build rule for target.
replaygain_synthesis/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/replaygain_synthesis/CMakeFiles/replaygain_synthesis.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/replaygain_synthesis/CMakeFiles/replaygain_synthesis.dir/build
.PHONY : replaygain_synthesis/fast

#=============================================================================
# Target rules for targets named getopt

# Build rule for target.
getopt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 getopt
.PHONY : getopt

# fast build rule for target.
getopt/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/getopt/CMakeFiles/getopt.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/getopt/CMakeFiles/getopt.dir/build
.PHONY : getopt/fast

#=============================================================================
# Target rules for targets named utf8

# Build rule for target.
utf8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utf8
.PHONY : utf8

# fast build rule for target.
utf8/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/utf8/CMakeFiles/utf8.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/utf8/CMakeFiles/utf8.dir/build
.PHONY : utf8/fast

#=============================================================================
# Target rules for targets named grabbag

# Build rule for target.
grabbag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grabbag
.PHONY : grabbag

# fast build rule for target.
grabbag/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/grabbag/CMakeFiles/grabbag.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/flac/src/share/grabbag/CMakeFiles/grabbag.dir/build
.PHONY : grabbag/fast

#=============================================================================
# Target rules for targets named vorbis

# Build rule for target.
vorbis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vorbis
.PHONY : vorbis

# fast build rule for target.
vorbis/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/vorbis/lib/CMakeFiles/vorbis.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/vorbis/lib/CMakeFiles/vorbis.dir/build
.PHONY : vorbis/fast

#=============================================================================
# Target rules for targets named vorbisenc

# Build rule for target.
vorbisenc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vorbisenc
.PHONY : vorbisenc

# fast build rule for target.
vorbisenc/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/vorbis/lib/CMakeFiles/vorbisenc.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/vorbis/lib/CMakeFiles/vorbisenc.dir/build
.PHONY : vorbisenc/fast

#=============================================================================
# Target rules for targets named vorbisfile

# Build rule for target.
vorbisfile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vorbisfile
.PHONY : vorbisfile

# fast build rule for target.
vorbisfile/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/vorbis/lib/CMakeFiles/vorbisfile.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/vorbis/lib/CMakeFiles/vorbisfile.dir/build
.PHONY : vorbisfile/fast

#=============================================================================
# Target rules for targets named kissfft

# Build rule for target.
kissfft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kissfft
.PHONY : kissfft

# fast build rule for target.
kissfft/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2atk/external/kissfft/CMakeFiles/kissfft.dir/build.make cugl.dir/sdl2pckg.dir/sdl2atk/external/kissfft/CMakeFiles/kissfft.dir/build
.PHONY : kissfft/fast

#=============================================================================
# Target rules for targets named SDL2_app

# Build rule for target.
SDL2_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_app
.PHONY : SDL2_app

# fast build rule for target.
SDL2_app/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/sdl2pckg.dir/sdl2app/CMakeFiles/SDL2_app.dir/build.make cugl.dir/sdl2pckg.dir/sdl2app/CMakeFiles/SDL2_app.dir/build
.PHONY : SDL2_app/fast

#=============================================================================
# Target rules for targets named poly2tri

# Build rule for target.
poly2tri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poly2tri
.PHONY : poly2tri

# fast build rule for target.
poly2tri/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/poly2tri/CMakeFiles/poly2tri.dir/build.make cugl.dir/external/poly2tri/CMakeFiles/poly2tri.dir/build
.PHONY : poly2tri/fast

#=============================================================================
# Target rules for targets named datachannel

# Build rule for target.
datachannel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 datachannel
.PHONY : datachannel

# fast build rule for target.
datachannel/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/libdatachannel/CMakeFiles/datachannel.dir/build.make cugl.dir/external/libdatachannel/CMakeFiles/datachannel.dir/build
.PHONY : datachannel/fast

#=============================================================================
# Target rules for targets named usrsctp

# Build rule for target.
usrsctp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 usrsctp
.PHONY : usrsctp

# fast build rule for target.
usrsctp/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/libdatachannel/deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/build.make cugl.dir/external/libdatachannel/deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/build
.PHONY : usrsctp/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/libdatachannel/deps/openssl/crypto/CMakeFiles/crypto.dir/build.make cugl.dir/external/libdatachannel/deps/openssl/crypto/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named ssl

# Build rule for target.
ssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssl
.PHONY : ssl

# fast build rule for target.
ssl/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/libdatachannel/deps/openssl/ssl/CMakeFiles/ssl.dir/build.make cugl.dir/external/libdatachannel/deps/openssl/ssl/CMakeFiles/ssl.dir/build
.PHONY : ssl/fast

#=============================================================================
# Target rules for targets named srtp2

# Build rule for target.
srtp2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 srtp2
.PHONY : srtp2

# fast build rule for target.
srtp2/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/libdatachannel/deps/libsrtp/CMakeFiles/srtp2.dir/build.make cugl.dir/external/libdatachannel/deps/libsrtp/CMakeFiles/srtp2.dir/build
.PHONY : srtp2/fast

#=============================================================================
# Target rules for targets named juice

# Build rule for target.
juice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juice
.PHONY : juice

# fast build rule for target.
juice/fast:
	$(MAKE) $(MAKESILENT) -f cugl.dir/external/libdatachannel/deps/libjuice/CMakeFiles/juice.dir/build.make cugl.dir/external/libdatachannel/deps/libjuice/CMakeFiles/juice.dir/build
.PHONY : juice/fast

source/MJAnimationController.o: source/MJAnimationController.cpp.o
.PHONY : source/MJAnimationController.o

# target to build an object file
source/MJAnimationController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJAnimationController.cpp.o
.PHONY : source/MJAnimationController.cpp.o

source/MJAnimationController.i: source/MJAnimationController.cpp.i
.PHONY : source/MJAnimationController.i

# target to preprocess a source file
source/MJAnimationController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJAnimationController.cpp.i
.PHONY : source/MJAnimationController.cpp.i

source/MJAnimationController.s: source/MJAnimationController.cpp.s
.PHONY : source/MJAnimationController.s

# target to generate assembly for a file
source/MJAnimationController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJAnimationController.cpp.s
.PHONY : source/MJAnimationController.cpp.s

source/MJApp.o: source/MJApp.cpp.o
.PHONY : source/MJApp.o

# target to build an object file
source/MJApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJApp.cpp.o
.PHONY : source/MJApp.cpp.o

source/MJApp.i: source/MJApp.cpp.i
.PHONY : source/MJApp.i

# target to preprocess a source file
source/MJApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJApp.cpp.i
.PHONY : source/MJApp.cpp.i

source/MJApp.s: source/MJApp.cpp.s
.PHONY : source/MJApp.s

# target to generate assembly for a file
source/MJApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJApp.cpp.s
.PHONY : source/MJApp.cpp.s

source/MJAudioController.o: source/MJAudioController.cpp.o
.PHONY : source/MJAudioController.o

# target to build an object file
source/MJAudioController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJAudioController.cpp.o
.PHONY : source/MJAudioController.cpp.o

source/MJAudioController.i: source/MJAudioController.cpp.i
.PHONY : source/MJAudioController.i

# target to preprocess a source file
source/MJAudioController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJAudioController.cpp.i
.PHONY : source/MJAudioController.cpp.i

source/MJAudioController.s: source/MJAudioController.cpp.s
.PHONY : source/MJAudioController.s

# target to generate assembly for a file
source/MJAudioController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJAudioController.cpp.s
.PHONY : source/MJAudioController.cpp.s

source/MJClientScene.o: source/MJClientScene.cpp.o
.PHONY : source/MJClientScene.o

# target to build an object file
source/MJClientScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJClientScene.cpp.o
.PHONY : source/MJClientScene.cpp.o

source/MJClientScene.i: source/MJClientScene.cpp.i
.PHONY : source/MJClientScene.i

# target to preprocess a source file
source/MJClientScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJClientScene.cpp.i
.PHONY : source/MJClientScene.cpp.i

source/MJClientScene.s: source/MJClientScene.cpp.s
.PHONY : source/MJClientScene.s

# target to generate assembly for a file
source/MJClientScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJClientScene.cpp.s
.PHONY : source/MJClientScene.cpp.s

source/MJDiscardPile.o: source/MJDiscardPile.cpp.o
.PHONY : source/MJDiscardPile.o

# target to build an object file
source/MJDiscardPile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJDiscardPile.cpp.o
.PHONY : source/MJDiscardPile.cpp.o

source/MJDiscardPile.i: source/MJDiscardPile.cpp.i
.PHONY : source/MJDiscardPile.i

# target to preprocess a source file
source/MJDiscardPile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJDiscardPile.cpp.i
.PHONY : source/MJDiscardPile.cpp.i

source/MJDiscardPile.s: source/MJDiscardPile.cpp.s
.PHONY : source/MJDiscardPile.s

# target to generate assembly for a file
source/MJDiscardPile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJDiscardPile.cpp.s
.PHONY : source/MJDiscardPile.cpp.s

source/MJDiscardUIScene.o: source/MJDiscardUIScene.cpp.o
.PHONY : source/MJDiscardUIScene.o

# target to build an object file
source/MJDiscardUIScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJDiscardUIScene.cpp.o
.PHONY : source/MJDiscardUIScene.cpp.o

source/MJDiscardUIScene.i: source/MJDiscardUIScene.cpp.i
.PHONY : source/MJDiscardUIScene.i

# target to preprocess a source file
source/MJDiscardUIScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJDiscardUIScene.cpp.i
.PHONY : source/MJDiscardUIScene.cpp.i

source/MJDiscardUIScene.s: source/MJDiscardUIScene.cpp.s
.PHONY : source/MJDiscardUIScene.s

# target to generate assembly for a file
source/MJDiscardUIScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJDiscardUIScene.cpp.s
.PHONY : source/MJDiscardUIScene.cpp.s

source/MJGameOverScene.o: source/MJGameOverScene.cpp.o
.PHONY : source/MJGameOverScene.o

# target to build an object file
source/MJGameOverScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJGameOverScene.cpp.o
.PHONY : source/MJGameOverScene.cpp.o

source/MJGameOverScene.i: source/MJGameOverScene.cpp.i
.PHONY : source/MJGameOverScene.i

# target to preprocess a source file
source/MJGameOverScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJGameOverScene.cpp.i
.PHONY : source/MJGameOverScene.cpp.i

source/MJGameOverScene.s: source/MJGameOverScene.cpp.s
.PHONY : source/MJGameOverScene.s

# target to generate assembly for a file
source/MJGameOverScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJGameOverScene.cpp.s
.PHONY : source/MJGameOverScene.cpp.s

source/MJGameScene.o: source/MJGameScene.cpp.o
.PHONY : source/MJGameScene.o

# target to build an object file
source/MJGameScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJGameScene.cpp.o
.PHONY : source/MJGameScene.cpp.o

source/MJGameScene.i: source/MJGameScene.cpp.i
.PHONY : source/MJGameScene.i

# target to preprocess a source file
source/MJGameScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJGameScene.cpp.i
.PHONY : source/MJGameScene.cpp.i

source/MJGameScene.s: source/MJGameScene.cpp.s
.PHONY : source/MJGameScene.s

# target to generate assembly for a file
source/MJGameScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJGameScene.cpp.s
.PHONY : source/MJGameScene.cpp.s

source/MJHostScene.o: source/MJHostScene.cpp.o
.PHONY : source/MJHostScene.o

# target to build an object file
source/MJHostScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJHostScene.cpp.o
.PHONY : source/MJHostScene.cpp.o

source/MJHostScene.i: source/MJHostScene.cpp.i
.PHONY : source/MJHostScene.i

# target to preprocess a source file
source/MJHostScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJHostScene.cpp.i
.PHONY : source/MJHostScene.cpp.i

source/MJHostScene.s: source/MJHostScene.cpp.s
.PHONY : source/MJHostScene.s

# target to generate assembly for a file
source/MJHostScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJHostScene.cpp.s
.PHONY : source/MJHostScene.cpp.s

source/MJInputController.o: source/MJInputController.cpp.o
.PHONY : source/MJInputController.o

# target to build an object file
source/MJInputController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJInputController.cpp.o
.PHONY : source/MJInputController.cpp.o

source/MJInputController.i: source/MJInputController.cpp.i
.PHONY : source/MJInputController.i

# target to preprocess a source file
source/MJInputController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJInputController.cpp.i
.PHONY : source/MJInputController.cpp.i

source/MJInputController.s: source/MJInputController.cpp.s
.PHONY : source/MJInputController.s

# target to generate assembly for a file
source/MJInputController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJInputController.cpp.s
.PHONY : source/MJInputController.cpp.s

source/MJMenuScene.o: source/MJMenuScene.cpp.o
.PHONY : source/MJMenuScene.o

# target to build an object file
source/MJMenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJMenuScene.cpp.o
.PHONY : source/MJMenuScene.cpp.o

source/MJMenuScene.i: source/MJMenuScene.cpp.i
.PHONY : source/MJMenuScene.i

# target to preprocess a source file
source/MJMenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJMenuScene.cpp.i
.PHONY : source/MJMenuScene.cpp.i

source/MJMenuScene.s: source/MJMenuScene.cpp.s
.PHONY : source/MJMenuScene.s

# target to generate assembly for a file
source/MJMenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJMenuScene.cpp.s
.PHONY : source/MJMenuScene.cpp.s

source/MJNetworkController.o: source/MJNetworkController.cpp.o
.PHONY : source/MJNetworkController.o

# target to build an object file
source/MJNetworkController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJNetworkController.cpp.o
.PHONY : source/MJNetworkController.cpp.o

source/MJNetworkController.i: source/MJNetworkController.cpp.i
.PHONY : source/MJNetworkController.i

# target to preprocess a source file
source/MJNetworkController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJNetworkController.cpp.i
.PHONY : source/MJNetworkController.cpp.i

source/MJNetworkController.s: source/MJNetworkController.cpp.s
.PHONY : source/MJNetworkController.s

# target to generate assembly for a file
source/MJNetworkController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJNetworkController.cpp.s
.PHONY : source/MJNetworkController.cpp.s

source/MJPauseScene.o: source/MJPauseScene.cpp.o
.PHONY : source/MJPauseScene.o

# target to build an object file
source/MJPauseScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPauseScene.cpp.o
.PHONY : source/MJPauseScene.cpp.o

source/MJPauseScene.i: source/MJPauseScene.cpp.i
.PHONY : source/MJPauseScene.i

# target to preprocess a source file
source/MJPauseScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPauseScene.cpp.i
.PHONY : source/MJPauseScene.cpp.i

source/MJPauseScene.s: source/MJPauseScene.cpp.s
.PHONY : source/MJPauseScene.s

# target to generate assembly for a file
source/MJPauseScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPauseScene.cpp.s
.PHONY : source/MJPauseScene.cpp.s

source/MJPile.o: source/MJPile.cpp.o
.PHONY : source/MJPile.o

# target to build an object file
source/MJPile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPile.cpp.o
.PHONY : source/MJPile.cpp.o

source/MJPile.i: source/MJPile.cpp.i
.PHONY : source/MJPile.i

# target to preprocess a source file
source/MJPile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPile.cpp.i
.PHONY : source/MJPile.cpp.i

source/MJPile.s: source/MJPile.cpp.s
.PHONY : source/MJPile.s

# target to generate assembly for a file
source/MJPile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPile.cpp.s
.PHONY : source/MJPile.cpp.s

source/MJPlayer.o: source/MJPlayer.cpp.o
.PHONY : source/MJPlayer.o

# target to build an object file
source/MJPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPlayer.cpp.o
.PHONY : source/MJPlayer.cpp.o

source/MJPlayer.i: source/MJPlayer.cpp.i
.PHONY : source/MJPlayer.i

# target to preprocess a source file
source/MJPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPlayer.cpp.i
.PHONY : source/MJPlayer.cpp.i

source/MJPlayer.s: source/MJPlayer.cpp.s
.PHONY : source/MJPlayer.s

# target to generate assembly for a file
source/MJPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJPlayer.cpp.s
.PHONY : source/MJPlayer.cpp.s

source/MJScoreManager.o: source/MJScoreManager.cpp.o
.PHONY : source/MJScoreManager.o

# target to build an object file
source/MJScoreManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJScoreManager.cpp.o
.PHONY : source/MJScoreManager.cpp.o

source/MJScoreManager.i: source/MJScoreManager.cpp.i
.PHONY : source/MJScoreManager.i

# target to preprocess a source file
source/MJScoreManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJScoreManager.cpp.i
.PHONY : source/MJScoreManager.cpp.i

source/MJScoreManager.s: source/MJScoreManager.cpp.s
.PHONY : source/MJScoreManager.s

# target to generate assembly for a file
source/MJScoreManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJScoreManager.cpp.s
.PHONY : source/MJScoreManager.cpp.s

source/MJSettingScene.o: source/MJSettingScene.cpp.o
.PHONY : source/MJSettingScene.o

# target to build an object file
source/MJSettingScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJSettingScene.cpp.o
.PHONY : source/MJSettingScene.cpp.o

source/MJSettingScene.i: source/MJSettingScene.cpp.i
.PHONY : source/MJSettingScene.i

# target to preprocess a source file
source/MJSettingScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJSettingScene.cpp.i
.PHONY : source/MJSettingScene.cpp.i

source/MJSettingScene.s: source/MJSettingScene.cpp.s
.PHONY : source/MJSettingScene.s

# target to generate assembly for a file
source/MJSettingScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJSettingScene.cpp.s
.PHONY : source/MJSettingScene.cpp.s

source/MJSpecialTiles.o: source/MJSpecialTiles.cpp.o
.PHONY : source/MJSpecialTiles.o

# target to build an object file
source/MJSpecialTiles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJSpecialTiles.cpp.o
.PHONY : source/MJSpecialTiles.cpp.o

source/MJSpecialTiles.i: source/MJSpecialTiles.cpp.i
.PHONY : source/MJSpecialTiles.i

# target to preprocess a source file
source/MJSpecialTiles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJSpecialTiles.cpp.i
.PHONY : source/MJSpecialTiles.cpp.i

source/MJSpecialTiles.s: source/MJSpecialTiles.cpp.s
.PHONY : source/MJSpecialTiles.s

# target to generate assembly for a file
source/MJSpecialTiles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJSpecialTiles.cpp.s
.PHONY : source/MJSpecialTiles.cpp.s

source/MJTileSet.o: source/MJTileSet.cpp.o
.PHONY : source/MJTileSet.o

# target to build an object file
source/MJTileSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJTileSet.cpp.o
.PHONY : source/MJTileSet.cpp.o

source/MJTileSet.i: source/MJTileSet.cpp.i
.PHONY : source/MJTileSet.i

# target to preprocess a source file
source/MJTileSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJTileSet.cpp.i
.PHONY : source/MJTileSet.cpp.i

source/MJTileSet.s: source/MJTileSet.cpp.s
.PHONY : source/MJTileSet.s

# target to generate assembly for a file
source/MJTileSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/MJTileSet.cpp.s
.PHONY : source/MJTileSet.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mahsjong.dir/build.make CMakeFiles/mahsjong.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... sdl_headers_copy"
	@echo "... uninstall"
	@echo "... FLAC"
	@echo "... SDL2-static"
	@echo "... SDL2_app"
	@echo "... SDL2_atk"
	@echo "... SDL2_image"
	@echo "... SDL2_ttf"
	@echo "... SDL2main"
	@echo "... crypto"
	@echo "... cugl-audio"
	@echo "... cugl-core"
	@echo "... cugl-graphics"
	@echo "... cugl-netcode"
	@echo "... cugl-scene2"
	@echo "... datachannel"
	@echo "... freetype"
	@echo "... getopt"
	@echo "... grabbag"
	@echo "... harfbuzz"
	@echo "... harfbuzz-subset"
	@echo "... juice"
	@echo "... kissfft"
	@echo "... mahsjong"
	@echo "... ogg"
	@echo "... poly2tri"
	@echo "... replaygain_analysis"
	@echo "... replaygain_synthesis"
	@echo "... srtp2"
	@echo "... ssl"
	@echo "... usrsctp"
	@echo "... utf8"
	@echo "... vorbis"
	@echo "... vorbisenc"
	@echo "... vorbisfile"
	@echo "... source/MJAnimationController.o"
	@echo "... source/MJAnimationController.i"
	@echo "... source/MJAnimationController.s"
	@echo "... source/MJApp.o"
	@echo "... source/MJApp.i"
	@echo "... source/MJApp.s"
	@echo "... source/MJAudioController.o"
	@echo "... source/MJAudioController.i"
	@echo "... source/MJAudioController.s"
	@echo "... source/MJClientScene.o"
	@echo "... source/MJClientScene.i"
	@echo "... source/MJClientScene.s"
	@echo "... source/MJDiscardPile.o"
	@echo "... source/MJDiscardPile.i"
	@echo "... source/MJDiscardPile.s"
	@echo "... source/MJDiscardUIScene.o"
	@echo "... source/MJDiscardUIScene.i"
	@echo "... source/MJDiscardUIScene.s"
	@echo "... source/MJGameOverScene.o"
	@echo "... source/MJGameOverScene.i"
	@echo "... source/MJGameOverScene.s"
	@echo "... source/MJGameScene.o"
	@echo "... source/MJGameScene.i"
	@echo "... source/MJGameScene.s"
	@echo "... source/MJHostScene.o"
	@echo "... source/MJHostScene.i"
	@echo "... source/MJHostScene.s"
	@echo "... source/MJInputController.o"
	@echo "... source/MJInputController.i"
	@echo "... source/MJInputController.s"
	@echo "... source/MJMenuScene.o"
	@echo "... source/MJMenuScene.i"
	@echo "... source/MJMenuScene.s"
	@echo "... source/MJNetworkController.o"
	@echo "... source/MJNetworkController.i"
	@echo "... source/MJNetworkController.s"
	@echo "... source/MJPauseScene.o"
	@echo "... source/MJPauseScene.i"
	@echo "... source/MJPauseScene.s"
	@echo "... source/MJPile.o"
	@echo "... source/MJPile.i"
	@echo "... source/MJPile.s"
	@echo "... source/MJPlayer.o"
	@echo "... source/MJPlayer.i"
	@echo "... source/MJPlayer.s"
	@echo "... source/MJScoreManager.o"
	@echo "... source/MJScoreManager.i"
	@echo "... source/MJScoreManager.s"
	@echo "... source/MJSettingScene.o"
	@echo "... source/MJSettingScene.i"
	@echo "... source/MJSettingScene.s"
	@echo "... source/MJSpecialTiles.o"
	@echo "... source/MJSpecialTiles.i"
	@echo "... source/MJSpecialTiles.s"
	@echo "... source/MJTileSet.o"
	@echo "... source/MJTileSet.i"
	@echo "... source/MJTileSet.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

